### ISSUE TITLE
日期选择器中建议使用规范的format函数

### ISSUE THREAD

**Issue by HQidea** [yiminghe/gregorian-calendar-format#9]
see https://github.com/ant-design/ant-design/issues/1591

**Comment by yiminghe** [comment]
YYYY 周年(weekyear)

yyyy 年

**Comment by HQidea** [comment]
@yiminghe 你有看过[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Dates) 和 https://www.w3.org/TR/NOTE-datetime 吗？
现在的用法是不规范的，就连[moment.js](http://momentjs.com/)也没单独搞一套。不按标准来很难跟别的代码进行融合

**Comment by yiminghe** [comment]
有什么问题么，这个库是移植 java 的 http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

y Y 是不一样的

**Comment by HQidea** [comment]
@yiminghe 看取名就知道大概是来自java了，我大致看了一下，这个格式是java自己定的，并不是标准，有好多人问如何在java里使用ISO 8601的格式。。

有标准的格式为什么不用呢？

现在的问题是我要将日期选择器的值一模一样的显示在别的地方，只有两个选项，1.使用这个库，用一样的format格式来格式化时间，这可能造成之后维护者的学习成本增加，因为现在的格式不是标准的。每个人都得记两套不同的格式，而使用antd的人明显是写js的多于写java的 2. 使用moment.js，标准格式，更通用，但是format格式不一样了，除了造成阅读代码的人不解之外还会导致当format格式是变量时得有额外的映射关系。

**Comment by yiminghe** [comment]
嗯，不好意思，之前不知道 iso 8601。

 目前来说再做不兼容改动也晚了，需要的话在应用层做个封装转换吧
